knp_snappy:
    pdf:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"'
        options:
            page-size: A4
            margin-top: 0mm
            margin-bottom: 0mm
            margin-left: 0mm
            margin-right: 0mm
            encoding: UTF-8
    image:
        enabled: true
        binary: '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"'
        options: []
