parameters:
    textgears_default_language: 'en-US'
    logos_directory: '%kernel.project_dir%/public/uploads/logos'
    ai_script_path: '%kernel.project_dir%/learning_assistant/app.py'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $apiKey: '%env(IMGBB_API_KEY)%'
            $geminiApiKey: '%env(GEMINI_API_KEY)%'
            $groqApiKey: '%env(GROQ_API_KEY)%'
            $sentimentApiKey: '%env(SENTIMENT_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ProfanityFilterService:
        arguments:
            $apiKey: '%env(APIVERVE_API_KEY)%'

    App\Service\AiProcessManager:
        arguments:
            $scriptPath: '%ai_script_path%'

    App\EventSubscriber\AiStartupSubscriber: ~

    App\Service\TextGearsService:
        arguments:
            $apiKey: '%env(TEXTGEARS_API_KEY)%'
